# 별표찍기

print('* ******* *')
print('** ***** **')
print('*** *** ***')
print('**** * ****')
print('***** *****')
print('**** * ****')
print('*** *** ***')
print('** ***** **')
print('* ******* *')
print()
print('-----------')
print()
print('     *     ')
print('    ***    ')
print('   *****   ')
print('  *******  ')
print('    ***    ')
print('   *****   ')
print('  *******  ')
print('***********')
print('    | |    ')
print('****| |****')
print()
print('-----------')
print()
print('*   *    * ')
print('  *    *   ')
print('&&_________')