# 콘솔출력 - 엔터를 공백으로 변경 (줄바꿈x)
print('*',end=' ')
print('**',end=' ')
print('***',end=' ')
print('****',end=' ')
print('*****')

# 콘솔출력 - 공백을 슬래쉬로 변경 (줄바꿈x)
print('a','b','c')
print('a', 'b', 'c', sep='/')